### ISSUE TITLE
won game state

### ISSUE THREAD

**Issue by Zkekos** [dgkanatsios/PuzzleGameUnity#3]
Hi there. I know this is the old post, but maybe somebody still watching.
Is there any chance to change the script for this puzzle (probably somewhere on the line 250), so that won game state turns to "go to next level (outside of the puzzle)"?

Thanks

**Comment by dgkanatsios** [comment]
You can easily go to the desired Unity scene by using SceneManager.LoadAsync method

https://docs.unity3d.com/ScriptReference/SceneManagement.SceneManager.LoadSceneAsync.html

**Comment by Zkekos** [comment]
thanks for reply, but I don't see how can I go from inside the puzzle to LoadScene at the point when puzzle is solved. I am not coding capable, I use Playmaker with Unity, so unfortunately the only way for me to make this done is to get a script from someone, not the help for writing anything which is code, otherwise no help for me. (((

**Comment by Zkekos** [comment]
Thank you for reply. Unfortunately there is nothing at Unity SceneManager-LoadAsync script that could be obviously connected with your script. The explanation is missing, One need to know scripting to figured this out. Script is just self-explained, nothing about where, when and how you can implement it. Maybe you can read this easily and comprehend, but for someone who is not in that branch (I am artist, not programmer, hardly even work with Playmaker in Unity), the entire Unity scripting help site is useless, because it is written for people who already have certain level of programming knowledge. I will never understand how programmers think? Why they think that their explanations are clear and crisp when they are not. Do they ever try to look at something from the different angle? Its like they set a rules - if you want to enter our world you have to be one of us.

Thanks again, but I CANT  " easily go to the desired Unity scene by using", but you can, lucky you!

Greetings

Srecko Zitnik
 
    On Monday, December 16, 2019, 7:02:27 PM GMT+1, Dimitris-Ilias Gkanatsios <notifications@github.com> wrote:  
 
 
You can easily go to the desired Unity scene by using SceneManager.LoadAsync method

https://docs.unity3d.com/ScriptReference/SceneManagement.SceneManager.LoadSceneAsync.html
